Add assay contacts
nfdi4plants/arcCommander pull request #78
Opened 2021-11-15 16:36 UTC by omaus

- `arc assay person` functions added:
  - `register`: Register a person to an assay
  - `unregister`: Delete a person from an assay
  - `update`: Update a person from an assay with new metadata given
  - `edit`: Open a person from an assay and edit their metadata
  - `show`: Show the metadata of a person from an assay
  - `list`: Show all persons from all assays in this ARC
- some minor improvements on phrasing and readability included

2021-11-16 10:25 UTC, HLWeil requested changes
Could you also check what happens if a command fails between opening and closing the assay xlsx file?
If the file stays blocked by the stream, a `try .. finally` might be necessary

2021-11-16 10:25 UTC, HLWeil commented on src/ArcCommander/APIs/AssayAPI.fs
> +                |> MetaData.overwriteWithPersons "Investigation" <| doc
I think backward piping (BWP) is rarely used and therefore might decrease readability for most users. Maybe you could bind the above value first

2021-11-16 10:25 UTC, HLWeil commented on src/ArcCommander/APIs/AssayAPI.fs
> +                    |> MetaData.overwriteWithPersons "Investigation" <| doc
BWP (see above)

2021-11-16 10:25 UTC, HLWeil commented on src/ArcCommander/APIs/AssayAPI.fs
> +                |> MetaData.overwriteWithPersons "Investigation" <| doc
BWP (see above)

2021-11-16 10:25 UTC, HLWeil commented on src/ArcCommander/APIs/AssayAPI.fs
> +            API.Person.add persons person
Check if person already exists. E.g. `arc s person register` fails if person with the same name already exists. This should be handled consistently.

2021-11-16 10:25 UTC, HLWeil commented on src/ArcCommander/APIs/AssayAPI.fs
> +            |> MetaData.overwriteWithPersons "Investigation" <| doc
BWP (see above)

2021-11-16 10:25 UTC, HLWeil commented on src/ArcCommander/APIs/AssayAPI.fs
> +                |> MetaData.overwriteWithPersons "Investigation" <| doc
BWP (see above)

2021-11-16 16:15 UTC, omaus commented
> Could you also check what happens if a command fails between opening and closing the assay xlsx file? If the file stays blocked by the stream, a `try .. finally` might be necessary

Atm. it seems that it is not possible for the code to fail since all cases are covered and the AC prints a message with closing all file streams instead of failing. But this does _not_ mean that it is impossible in general.
Therefore, I will add `try finally`s.

2021-11-17 13:56 UTC, HLWeil approved these changes

2021-11-17 13:56 UTC, merged